# Generated by Django 5.0.6 on 2026-05-21 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_userprofile_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id_proveedor', models.IntegerField()),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('nombre_fiscal', models.CharField(blank=True, max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('cod_postal', models.CharField(blank=True, max_length=20)),
                ('poblacion', models.CharField(blank=True, max_length=120)),
                ('provincia', models.CharField(blank=True, max_length=120)),
                ('pais', models.CharField(blank=True, max_length=80)),
                ('cif', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=80)),
                ('contacto_comercial', models.CharField(blank=True, max_length=160)),
                ('tel_contacto_comercial', models.CharField(blank=True, max_length=80)),
                ('contacto_admin', models.CharField(blank=True, max_length=160)),
                ('tel_contacto_admin', models.CharField(blank=True, max_length=80)),
                ('sp_iva', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('es_subcontrata', models.BooleanField(default=False)),
                ('cod_obra_legacy', models.CharField(blank=True, max_length=50)),
                ('fuera_listado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_proveedores_creados', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestion_proveedores', to='usuarios.team')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_comercial'],
                'indexes': [models.Index(fields=['team', 'nombre_comercial'], name='gestion_pro_team_id_bb238d_idx'), models.Index(fields=['team', 'cif'], name='gestion_pro_team_id_37c83f_idx'), models.Index(fields=['team', 'legacy_id_proveedor'], name='gestion_pro_team_id_3a877b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('team', 'legacy_id_proveedor'), name='uniq_gestion_proveedor_team_legacy'),
        ),
    ]
