# Generated by Django 5.0.6 on 2026-05-21 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_create_proveedor'),
        ('usuarios', '0004_alter_userprofile_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaGestionLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id_empresa', models.IntegerField(unique=True)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('cif_empresa', models.CharField(blank=True, max_length=50)),
                ('direccion_empresa', models.CharField(blank=True, max_length=255)),
                ('poblacion_empresa', models.CharField(blank=True, max_length=120)),
                ('provincia_empresa', models.CharField(blank=True, max_length=120)),
                ('cod_postal_empresa', models.CharField(blank=True, max_length=20)),
                ('periodo_gestion', models.CharField(blank=True, max_length=20)),
                ('ult_codigo_factura', models.IntegerField(default=0)),
                ('prefijo_factura', models.CharField(blank=True, max_length=20)),
                ('ult_codigo_albaran', models.IntegerField(default=0)),
                ('prefijo_albaran', models.CharField(blank=True, max_length=20)),
                ('obra_defecto_legacy', models.IntegerField(default=0)),
                ('prefijo_pedido', models.CharField(blank=True, max_length=20)),
                ('ult_codigo_pedido', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='empresa_gestion_legacy', to='usuarios.team')),
            ],
            options={
                'verbose_name': 'Empresa legacy de gestión',
                'verbose_name_plural': 'Empresas legacy de gestión',
                'ordering': ['legacy_id_empresa'],
                'indexes': [models.Index(fields=['legacy_id_empresa'], name='gestion_emp_legacy__e8b6d9_idx'), models.Index(fields=['team'], name='gestion_emp_team_id_94d8e0_idx'), models.Index(fields=['cif_empresa'], name='gestion_emp_cif_emp_335bcd_idx')],
            },
        ),
    ]
