# Generated by Django 5.0.6 on 2026-05-21 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_add_empresa_gestion_legacy'),
        ('usuarios', '0004_alter_userprofile_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaProveedorGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_factura', models.CharField(max_length=50)),
                ('cod_obra_legacy', models.CharField(blank=True, max_length=50)),
                ('cod_proveedor_legacy', models.IntegerField(blank=True, null=True)),
                ('empresa_legacy_raw', models.IntegerField(blank=True, null=True)),
                ('num_factura_proveedor', models.CharField(blank=True, max_length=120)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_autorizacion_gerencia', models.DateField(blank=True, null=True)),
                ('fecha_pago_segun_contrato', models.DateField(blank=True, null=True)),
                ('fecha_real_pago', models.DateField(blank=True, null=True)),
                ('importe_base_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('importe_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('importe_factura', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('retencion', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('importe_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('forma_pago', models.CharField(blank=True, max_length=160)),
                ('estado', models.CharField(blank=True, max_length=80)),
                ('observaciones', models.TextField(blank=True)),
                ('asignada', models.BooleanField(default=False)),
                ('tiene_retencion', models.BooleanField(default=False)),
                ('generado_albaran', models.BooleanField(default=False)),
                ('certificada', models.BooleanField(default=False)),
                ('archivo', models.CharField(blank=True, max_length=255)),
                ('archivo1', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa_legacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_proveedor', to='gestion.empresagestionlegacy')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_gestion', to='gestion.proveedor')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestion_facturas_proveedor', to='usuarios.team')),
            ],
            options={
                'verbose_name': 'Factura de proveedor',
                'verbose_name_plural': 'Facturas de proveedores',
                'ordering': ['-fecha_emision', '-cod_factura'],
                'indexes': [models.Index(fields=['team', 'cod_factura'], name='gestion_fac_team_id_9792cf_idx'), models.Index(fields=['team', 'fecha_emision'], name='gestion_fac_team_id_ad01fe_idx'), models.Index(fields=['team', 'estado'], name='gestion_fac_team_id_2bb870_idx'), models.Index(fields=['team', 'proveedor'], name='gestion_fac_team_id_b34f29_idx'), models.Index(fields=['empresa_legacy_raw'], name='gestion_fac_empresa_413160_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='facturaproveedorgestion',
            constraint=models.UniqueConstraint(fields=('team', 'cod_factura'), name='uniq_gestion_factura_team_cod'),
        ),
    ]
