# Generated by Django 5.0.6 on 2026-05-21 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_add_factura_proveedor_gestion'),
        ('usuarios', '0004_alter_userprofile_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbaranProveedorGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_albaran', models.CharField(max_length=50)),
                ('cod_obra_legacy', models.CharField(blank=True, max_length=50)),
                ('cod_proveedor_legacy', models.IntegerField(blank=True, null=True)),
                ('empresa_legacy_raw', models.IntegerField(blank=True, null=True)),
                ('num_albaran_proveedor', models.CharField(blank=True, max_length=120)),
                ('fecha_albaran', models.DateField(blank=True, null=True)),
                ('fecha_entrega_mercaderia', models.DateField(blank=True, null=True)),
                ('importe_albaran', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('importe_asignado_factura', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descripcion', models.TextField(blank=True)),
                ('recepcionado_por', models.CharField(blank=True, max_length=160)),
                ('presupuesto', models.BooleanField(default=False)),
                ('cod_presupuesto_legacy', models.CharField(blank=True, max_length=50)),
                ('ok_presupuesto', models.BooleanField(default=False)),
                ('autorizado_jefe_obra', models.BooleanField(default=False)),
                ('asignado_partida_obra', models.BooleanField(default=False)),
                ('asignado_factura', models.BooleanField(default=False)),
                ('lineas_asignadas', models.IntegerField(default=0)),
                ('situacion', models.CharField(blank=True, max_length=80)),
                ('archivo', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa_legacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='albaranes_proveedor', to='gestion.empresagestionlegacy')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albaranes_gestion', to='gestion.proveedor')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestion_albaranes_proveedor', to='usuarios.team')),
            ],
            options={
                'verbose_name': 'Albarán de proveedor',
                'verbose_name_plural': 'Albaranes de proveedores',
                'ordering': ['-fecha_albaran', '-cod_albaran'],
                'indexes': [models.Index(fields=['team', 'cod_albaran'], name='gestion_alb_team_id_a16a23_idx'), models.Index(fields=['team', 'fecha_albaran'], name='gestion_alb_team_id_bbe1c5_idx'), models.Index(fields=['team', 'proveedor'], name='gestion_alb_team_id_139649_idx'), models.Index(fields=['team', 'asignado_factura'], name='gestion_alb_team_id_2c08a8_idx'), models.Index(fields=['empresa_legacy_raw'], name='gestion_alb_empresa_a82999_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='albaranproveedorgestion',
            constraint=models.UniqueConstraint(fields=('team', 'cod_albaran'), name='uniq_gestion_albaran_team_cod'),
        ),
    ]
