# Generated by Django 5.0.6 on 2026-05-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_add_albaran_proveedor_gestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaProveedorLineaGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.IntegerField()),
                ('cod_articulo_legacy', models.IntegerField(blank=True, null=True)),
                ('cod_albaran_legacy', models.CharField(blank=True, max_length=50)),
                ('linea_albaran_legacy', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('importe_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('importe_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('en_partida', models.BooleanField(default=False)),
                ('cantidad_en_partidas', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('en_almacen', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('albaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_factura', to='gestion.albaranproveedorgestion')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='gestion.facturaproveedorgestion')),
            ],
            options={
                'verbose_name': 'Línea de factura de proveedor',
                'verbose_name_plural': 'Líneas de facturas de proveedores',
                'ordering': ['factura', 'linea'],
            },
        ),
        migrations.CreateModel(
            name='AlbaranProveedorLineaGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.IntegerField()),
                ('cod_articulo_legacy', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unidad', models.CharField(blank=True, max_length=30)),
                ('cantidad_compra', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unidad_compra', models.CharField(blank=True, max_length=30)),
                ('cantidad_x_unidad', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('importe_linea', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('facturado', models.BooleanField(default=False)),
                ('factura_legacy', models.CharField(blank=True, max_length=50)),
                ('en_pedido', models.BooleanField(default=False)),
                ('en_partida', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('recepcionado_por', models.CharField(blank=True, max_length=160)),
                ('importe_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('id_almacen_legacy', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('tipo_recurso', models.CharField(blank=True, max_length=80)),
                ('cantidad_en_partidas', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('en_almacen', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('albaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='gestion.albaranproveedorgestion')),
            ],
            options={
                'verbose_name': 'Línea de albarán de proveedor',
                'verbose_name_plural': 'Líneas de albaranes de proveedores',
                'ordering': ['albaran', 'linea'],
                'indexes': [models.Index(fields=['albaran', 'linea'], name='gestion_alb_albaran_34d8cd_idx'), models.Index(fields=['cod_articulo_legacy'], name='gestion_alb_cod_art_07d4ea_idx'), models.Index(fields=['facturado'], name='gestion_alb_factura_eb867d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='albaranproveedorlineagestion',
            constraint=models.UniqueConstraint(fields=('albaran', 'linea'), name='uniq_gestion_albaran_linea'),
        ),
        migrations.AddIndex(
            model_name='facturaproveedorlineagestion',
            index=models.Index(fields=['factura', 'linea'], name='gestion_fac_factura_c7d769_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaproveedorlineagestion',
            index=models.Index(fields=['albaran'], name='gestion_fac_albaran_54aa13_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaproveedorlineagestion',
            index=models.Index(fields=['cod_articulo_legacy'], name='gestion_fac_cod_art_df8591_idx'),
        ),
        migrations.AddConstraint(
            model_name='facturaproveedorlineagestion',
            constraint=models.UniqueConstraint(fields=('factura', 'linea'), name='uniq_gestion_factura_linea'),
        ),
    ]
