# Generated by Django 5.0.6 on 2026-05-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_add_lineas_facturas_albaranes'),
        ('usuarios', '0004_alter_userprofile_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaAlbaranGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_asignado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('albaran', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_vinculadas', to='gestion.albaranproveedorgestion')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albaranes_vinculados', to='gestion.facturaproveedorgestion')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestion_factura_albaran_vinculos', to='usuarios.team')),
            ],
            options={
                'verbose_name': 'Vínculo factura-albarán',
                'verbose_name_plural': 'Vínculos factura-albarán',
                'ordering': ['factura', 'albaran'],
                'indexes': [models.Index(fields=['team', 'factura'], name='gestion_fac_team_id_619663_idx'), models.Index(fields=['team', 'albaran'], name='gestion_fac_team_id_ba9c17_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='facturaalbarangestion',
            constraint=models.UniqueConstraint(fields=('factura', 'albaran'), name='uniq_gestion_factura_albaran'),
        ),
    ]
