# Generated by Django 5.0.6 on 2026-05-27 14:16

import apps.gestion.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_add_factura_albaran_vinculo'),
        ('usuarios', '0004_alter_userprofile_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCompraAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=500, upload_to=apps.gestion.models.gestion_compra_adjunto_upload_to)),
                ('tipo_documento', models.CharField(choices=[('FACTURA_PDF', 'PDF factura'), ('ALBARAN_PDF', 'PDF albarán'), ('ANEXO', 'Anexo'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('nombre_original', models.CharField(max_length=255)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ocr_estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('NO_APLICA', 'No aplica'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('ocr_texto', models.TextField(blank=True)),
                ('ocr_json', models.JSONField(blank=True, null=True)),
                ('ocr_error', models.TextField(blank=True)),
                ('albaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='gestion.albaranproveedorgestion')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='gestion.facturaproveedorgestion')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_documentos_compra_subidos', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestion_documentos_compra', to='usuarios.team')),
            ],
            options={
                'verbose_name': 'Documento adjunto de compra',
                'verbose_name_plural': 'Documentos adjuntos de compra',
                'ordering': ['-creado_en', '-id'],
                'indexes': [models.Index(fields=['team', 'tipo_documento'], name='gestion_doc_team_id_fa043d_idx'), models.Index(fields=['factura'], name='gestion_doc_factura_edd801_idx'), models.Index(fields=['albaran'], name='gestion_doc_albaran_957793_idx'), models.Index(fields=['ocr_estado'], name='gestion_doc_ocr_est_addf42_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentocompraadjunto',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('albaran__isnull', True), ('factura__isnull', False)), models.Q(('albaran__isnull', False), ('factura__isnull', True)), _connector='OR'), name='gestion_adjunto_factura_o_albaran'),
        ),
    ]
