# Generated by Django 5.0.6 on 2026-06-03 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_documentocompraadjunto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionAccessSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(max_length=500)),
                ('mode', models.CharField(choices=[('DRY_RUN', 'Dry-run'), ('COMMIT', 'Commit')], max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'En ejecución'), ('OK', 'Correcto'), ('ERROR', 'Error')], default='RUNNING', max_length=20)),
                ('backup_path', models.CharField(blank=True, max_length=500)),
                ('output_text', models.TextField(blank=True)),
                ('error_text', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
