# Generated by Django 5.0.6 on 2026-06-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_gestionaccesssyncrun'),
        ('usuarios', '0004_alter_userprofile_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloProveedorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(max_length=120)),
                ('descripcion_proveedor', models.CharField(blank=True, max_length=500)),
                ('unidad_proveedor', models.CharField(blank=True, max_length=40)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VINCULADO', 'Vinculado'), ('IGNORADO', 'Ignorado')], default='VINCULADO', max_length=20)),
                ('ultimo_precio', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('ultima_fecha', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alias de artículo por proveedor',
                'verbose_name_plural': 'Alias de artículos por proveedor',
                'ordering': ['proveedor', 'codigo_proveedor'],
            },
        ),
        migrations.CreateModel(
            name='ArticuloCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad', models.CharField(blank=True, max_length=40)),
                ('tipo', models.CharField(blank=True, default='MATERIAL', max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('recurso_catalogo_id', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestion_articulos_compra', to='usuarios.team')),
            ],
            options={
                'verbose_name': 'Artículo de compra',
                'verbose_name_plural': 'Artículos de compra',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='albaranproveedorlineagestion',
            name='articulo_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_albaran', to='gestion.articulocompra'),
        ),
        migrations.AddField(
            model_name='facturaproveedorlineagestion',
            name='articulo_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_factura', to='gestion.articulocompra'),
        ),
        migrations.AddIndex(
            model_name='albaranproveedorlineagestion',
            index=models.Index(fields=['articulo_compra'], name='gestion_alb_articul_f93509_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaproveedorlineagestion',
            index=models.Index(fields=['articulo_compra'], name='gestion_fac_articul_3260d2_idx'),
        ),
        migrations.AddField(
            model_name='articuloproveedoralias',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alias_proveedor', to='gestion.articulocompra'),
        ),
        migrations.AddField(
            model_name='articuloproveedoralias',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos_alias', to='gestion.proveedor'),
        ),
        migrations.AddField(
            model_name='articuloproveedoralias',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestion_articulos_alias', to='usuarios.team'),
        ),
        migrations.AddIndex(
            model_name='articulocompra',
            index=models.Index(fields=['team', 'nombre'], name='gestion_art_team_id_8a751d_idx'),
        ),
        migrations.AddIndex(
            model_name='articulocompra',
            index=models.Index(fields=['team', 'activo'], name='gestion_art_team_id_334795_idx'),
        ),
        migrations.AddIndex(
            model_name='articulocompra',
            index=models.Index(fields=['recurso_catalogo_id'], name='gestion_art_recurso_5fd08d_idx'),
        ),
        migrations.AddConstraint(
            model_name='articulocompra',
            constraint=models.UniqueConstraint(fields=('team', 'nombre'), name='uniq_gestion_articulo_compra_team_nombre'),
        ),
        migrations.AddIndex(
            model_name='articuloproveedoralias',
            index=models.Index(fields=['team', 'proveedor'], name='gestion_art_team_id_a92234_idx'),
        ),
        migrations.AddIndex(
            model_name='articuloproveedoralias',
            index=models.Index(fields=['team', 'codigo_proveedor'], name='gestion_art_team_id_f9904b_idx'),
        ),
        migrations.AddIndex(
            model_name='articuloproveedoralias',
            index=models.Index(fields=['articulo'], name='gestion_art_articul_0c2251_idx'),
        ),
        migrations.AddIndex(
            model_name='articuloproveedoralias',
            index=models.Index(fields=['estado'], name='gestion_art_estado_b7ce25_idx'),
        ),
        migrations.AddConstraint(
            model_name='articuloproveedoralias',
            constraint=models.UniqueConstraint(fields=('team', 'proveedor', 'codigo_proveedor'), name='uniq_gestion_alias_team_proveedor_codigo'),
        ),
    ]
