# Generated by Django 5.0.6 on 2026-06-18 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_articulos_compra_alias'),
        ('usuarios', '0004_alter_userprofile_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaOCRProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('ALBARAN', 'Albarán'), ('FACTURA', 'Factura')], db_index=True, max_length=20)),
                ('codigo', models.CharField(help_text='Código interno estable de plantilla, por ejemplo divelec_albaran_valorado_v1.', max_length=80)),
                ('nombre', models.CharField(max_length=160)),
                ('variante', models.CharField(blank=True, max_length=120)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('prioridad', models.PositiveIntegerField(default=100)),
                ('parser_key', models.CharField(help_text='Clave del parser a aplicar para esta plantilla.', max_length=120)),
                ('valorado_default', models.BooleanField(default=True, help_text='Indica si por defecto las líneas vienen valoradas con precio/importe.')),
                ('detector_texto', models.TextField(blank=True, help_text='Texto orientativo esperado para comprobar si el PDF parece coincidir con la plantilla.')),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Configuración flexible de regex, columnas, totales y reglas de líneas.')),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_ocr', to='gestion.proveedor')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_ocr_proveedor', to='usuarios.team')),
            ],
            options={
                'verbose_name': 'Plantilla OCR de proveedor',
                'verbose_name_plural': 'Plantillas OCR de proveedor',
                'ordering': ['team', 'proveedor', 'tipo_documento', 'prioridad', 'nombre'],
                'indexes': [models.Index(fields=['team', 'tipo_documento', 'activa'], name='idx_gocr_tpl_team_tipo_act'), models.Index(fields=['proveedor', 'tipo_documento', 'activa'], name='idx_gocr_tpl_prov_tipo_act')],
            },
        ),
        migrations.AddConstraint(
            model_name='plantillaocrproveedor',
            constraint=models.UniqueConstraint(fields=('team', 'proveedor', 'tipo_documento', 'codigo'), name='uniq_gestion_ocr_tpl_proveedor_tipo_codigo'),
        ),
    ]
