# Generated by Django 5.0.6 on 2026-06-24 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_plantillaocrproveedor_and_more'),
        ('usuarios', '0004_alter_userprofile_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='albaranproveedorgestion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_albaranes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='albaranproveedorgestion',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_albaranes_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='albaranproveedorgestion',
            name='origen_alta',
            field=models.CharField(blank=True, choices=[('LEGACY', 'Legacy / importación histórica'), ('MANUAL', 'Manual'), ('PDF_OCR', 'PDF / OCR'), ('SYNC_ACCESS', 'Sincronización MS Access'), ('SISTEMA', 'Sistema')], default='LEGACY', max_length=30),
        ),
        migrations.AddField(
            model_name='albaranproveedorlineagestion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_lineas_albaran_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='albaranproveedorlineagestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='albaranproveedorlineagestion',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_lineas_albaran_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='albaranproveedorlineagestion',
            name='origen_alta',
            field=models.CharField(blank=True, default='LEGACY', max_length=30),
        ),
        migrations.AddField(
            model_name='albaranproveedorlineagestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaalbarangestion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_vinculos_factura_albaran_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturaalbarangestion',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_vinculos_factura_albaran_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturaalbarangestion',
            name='origen_alta',
            field=models.CharField(blank=True, default='LEGACY', max_length=30),
        ),
        migrations.AddField(
            model_name='facturaproveedorgestion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_facturas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturaproveedorgestion',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_facturas_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturaproveedorgestion',
            name='origen_alta',
            field=models.CharField(blank=True, choices=[('LEGACY', 'Legacy / importación histórica'), ('MANUAL', 'Manual'), ('PDF_OCR', 'PDF / OCR'), ('SYNC_ACCESS', 'Sincronización MS Access'), ('SISTEMA', 'Sistema')], default='LEGACY', max_length=30),
        ),
        migrations.AddField(
            model_name='facturaproveedorlineagestion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_lineas_factura_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturaproveedorlineagestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaproveedorlineagestion',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_lineas_factura_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturaproveedorlineagestion',
            name='origen_alta',
            field=models.CharField(blank=True, default='LEGACY', max_length=30),
        ),
        migrations.AddField(
            model_name='facturaproveedorlineagestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='GestionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREADO', 'Creado'), ('MODIFICADO', 'Modificado'), ('ELIMINADO', 'Eliminado'), ('PDF_SUBIDO', 'PDF subido'), ('OCR_LEIDO', 'OCR leído'), ('LINEAS_OCR_IMPORTADAS', 'Líneas OCR importadas'), ('RECALCULO_IMPORTES', 'Recálculo de importes'), ('VINCULO_CREADO', 'Vínculo creado'), ('VINCULO_ELIMINADO', 'Vínculo eliminado'), ('BACKFILL', 'Backfill trazabilidad')], max_length=60)),
                ('entidad', models.CharField(max_length=120)),
                ('objeto_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('objeto_repr', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='gestion.documentocompraadjunto')),
                ('albaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='gestion.albaranproveedorgestion')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='gestion.facturaproveedorgestion')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.team')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['entidad', 'objeto_id'], name='gestion_ges_entidad_15576f_idx'), models.Index(fields=['accion', 'created_at'], name='gestion_ges_accion_4c22bd_idx'), models.Index(fields=['team', 'created_at'], name='gestion_ges_team_id_3b202c_idx')],
            },
        ),
    ]
