# Generated by Django 5.0.6 on 2026-06-24 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_trazabilidad_v1'),
        ('planificacion_obra', '0008_alter_asignacionobra_options_and_more'),
        ('usuarios', '0004_alter_userprofile_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='albaranproveedorgestion',
            name='ambito_gestion',
            field=models.CharField(blank=True, choices=[('SIN_CLASIFICAR', 'Sin clasificar'), ('OBRA', 'Obra'), ('ADMINISTRACION', 'Administración'), ('COMERCIAL', 'Comercial'), ('GERENCIA', 'Gerencia'), ('INFORMATICA', 'Informática'), ('VEHICULOS', 'Vehículos'), ('ALQUILERES', 'Alquileres'), ('SERVICIOS_GENERALES', 'Servicios generales'), ('OTROS', 'Otros')], default='SIN_CLASIFICAR', max_length=40),
        ),
        migrations.AddField(
            model_name='albaranproveedorgestion',
            name='obra_planificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albaranes_gestion', to='planificacion_obra.obraplanificacion'),
        ),
        migrations.AddField(
            model_name='facturaproveedorgestion',
            name='ambito_gestion',
            field=models.CharField(blank=True, choices=[('SIN_CLASIFICAR', 'Sin clasificar'), ('OBRA', 'Obra'), ('ADMINISTRACION', 'Administración'), ('COMERCIAL', 'Comercial'), ('GERENCIA', 'Gerencia'), ('INFORMATICA', 'Informática'), ('VEHICULOS', 'Vehículos'), ('ALQUILERES', 'Alquileres'), ('SERVICIOS_GENERALES', 'Servicios generales'), ('OTROS', 'Otros')], default='SIN_CLASIFICAR', max_length=40),
        ),
        migrations.AddField(
            model_name='facturaproveedorgestion',
            name='obra_planificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_gestion', to='planificacion_obra.obraplanificacion'),
        ),
        migrations.CreateModel(
            name='CentroCosteGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('SIN_CLASIFICAR', 'Sin clasificar'), ('OBRA', 'Obra'), ('ADMINISTRACION', 'Administración'), ('COMERCIAL', 'Comercial'), ('GERENCIA', 'Gerencia'), ('INFORMATICA', 'Informática'), ('VEHICULOS', 'Vehículos'), ('ALQUILERES', 'Alquileres'), ('SERVICIOS_GENERALES', 'Servicios generales'), ('OTROS', 'Otros')], default='SIN_CLASIFICAR', max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_coste_gestion_creados', to=settings.AUTH_USER_MODEL)),
                ('obra_planificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_coste_gestion', to='planificacion_obra.obraplanificacion')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_coste_gestion', to='usuarios.team')),
            ],
            options={
                'ordering': ['team__name', 'tipo', 'codigo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='albaranproveedorgestion',
            name='centro_coste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albaranes', to='gestion.centrocostegestion'),
        ),
        migrations.AddField(
            model_name='facturaproveedorgestion',
            name='centro_coste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='gestion.centrocostegestion'),
        ),
        migrations.AddIndex(
            model_name='centrocostegestion',
            index=models.Index(fields=['team', 'tipo'], name='gestion_cen_team_id_5ee809_idx'),
        ),
        migrations.AddIndex(
            model_name='centrocostegestion',
            index=models.Index(fields=['team', 'activo'], name='gestion_cen_team_id_86f6a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='centrocostegestion',
            constraint=models.UniqueConstraint(fields=('team', 'codigo'), name='uniq_gestion_centro_coste_team_codigo'),
        ),
    ]
