# Generated by Django 5.0.6 on 2026-06-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_centro_coste_gestion_v1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albaranproveedorgestion',
            name='ambito_gestion',
            field=models.CharField(blank=True, choices=[('SIN_CLASIFICAR', 'Sin clasificar'), ('OBRA', 'Obra'), ('ADMINISTRACION', 'Administración'), ('COMERCIAL', 'Comercial'), ('GERENCIA', 'Gerencia'), ('INFORMATICA', 'Informática'), ('VEHICULOS', 'Vehículos'), ('ALQUILERES', 'Alquileres'), ('SERVICIOS_GENERALES', 'Servicios generales'), ('OTROS', 'Otros')], default='OBRA', max_length=40),
        ),
        migrations.AlterField(
            model_name='facturaproveedorgestion',
            name='ambito_gestion',
            field=models.CharField(blank=True, choices=[('SIN_CLASIFICAR', 'Sin clasificar'), ('OBRA', 'Obra'), ('ADMINISTRACION', 'Administración'), ('COMERCIAL', 'Comercial'), ('GERENCIA', 'Gerencia'), ('INFORMATICA', 'Informática'), ('VEHICULOS', 'Vehículos'), ('ALQUILERES', 'Alquileres'), ('SERVICIOS_GENERALES', 'Servicios generales'), ('OTROS', 'Otros')], default='OBRA', max_length=40),
        ),
    ]
