# Generated by Django 5.0.6 on 2026-06-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_ambito_obra_default_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='ambito_gestion',
            field=models.CharField(blank=True, db_index=True, default='OBRA', help_text='Ámbito operativo principal del proveedor para filtrar altas y OCR.', max_length=40),
        ),
    ]
