# Generated by Django 5.0.6 on 2025-12-08 12:14

import archivos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('visibilidad', models.CharField(choices=[('GLOBAL', 'Global (toda la empresa)'), ('DEPTO', 'Departamento'), ('PRIVADA', 'Privada / personal')], default='GLOBAL', max_length=20)),
                ('departamento', models.CharField(blank=True, help_text='Opcional: nombre del departamento dueño de la carpeta.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carpetas_propias', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijas', to='archivos.carpeta')),
            ],
            options={
                'verbose_name': 'carpeta',
                'verbose_name_plural': 'carpetas',
                'ordering': ['parent__id', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichero', models.FileField(upload_to=archivos.models.archivo_upload_to)),
                ('nombre_original', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='archivos.carpeta')),
            ],
            options={
                'verbose_name': 'archivo',
                'verbose_name_plural': 'archivos',
                'ordering': ['-created_at'],
            },
        ),
    ]
