# Generated by Django 5.0.6 on 2025-12-08 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Grupo / departamento propietario de la carpeta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carpetas', to='auth.group'),
        ),
    ]
