# Generated by Django 5.0.6 on 2026-02-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_alter_carpeta_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='nombre_logico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivo',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
