# Generated by Django 5.0.6 on 2026-02-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0003_archivo_nombre_logico_archivo_version'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archivo',
            unique_together={('carpeta', 'nombre_logico', 'version')},
        ),
    ]
