# Generated by Django 5.0.6 on 2026-02-20 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0004_alter_archivo_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('SUBIR', 'Subida'), ('RENOMBRAR', 'Renombrar'), ('MOVER', 'Mover'), ('ELIMINAR', 'Eliminar'), ('DESCARGAR', 'Descargar')], max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='archivos.archivo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivo_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'log de archivo',
                'verbose_name_plural': 'logs de archivo',
                'ordering': ['-fecha'],
            },
        ),
    ]
