# Generated by Django 5.0.6 on 2026-07-15 06:45

import archivos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0005_archivolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='archivo',
            name='storage_key',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='archivo',
            name='storage_object_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='archivo',
            name='storage_provider',
            field=models.CharField(db_index=True, default='local', max_length=32),
        ),
        migrations.AddField(
            model_name='archivo',
            name='storage_version',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='fichero',
            field=models.FileField(blank=True, upload_to=archivos.models.archivo_upload_to),
        ),
    ]
