# Generated by Django 5.0.6 on 2026-07-18 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0006_storage_reference_generic'),
        ('usuarios', '0004_alter_userprofile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece el documento. No representa al usuario que realizó la operación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_documentales', to='usuarios.team'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Empresa propietaria del ámbito documental. Puede quedar vacío para documentación compartida o todavía no clasificada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carpetas_documentales', to='usuarios.team'),
        ),
    ]
