# Generated by Django 5.0.6 on 2026-07-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0008_cloud_folder_upload_permission'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaAccesoRaizCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_raiz', models.CharField(help_text='Nombre exacto de la carpeta raíz visible mediante INTASA Cloud.', max_length=255, unique=True, verbose_name='Raíz documental')),
                ('visible_para_todos', models.BooleanField(default=False, help_text='Permite esta raíz a cualquier usuario que tenga la capacidad documental requerida.', verbose_name='Visible para todos los usuarios con acceso')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grupos', models.ManyToManyField(blank=True, related_name='reglas_acceso_raiz_cloud', to='auth.group', verbose_name='Grupos autorizados')),
            ],
            options={
                'verbose_name': 'Regla de acceso a raíz Cloud',
                'verbose_name_plural': 'Reglas de acceso a raíces Cloud',
                'ordering': ('nombre_raiz',),
            },
        ),
    ]
