# Generated by Django 5.0.6 on 2026-02-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0003_archivo_nombre_logico_archivo_version_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archivo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='nombre_logico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
