# Generated by Django 5.0.6 on 2026-05-10 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_userprofile_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=80)),
                ('nombre_completo', models.CharField(max_length=220)),
                ('nif_nie', models.CharField(blank=True, max_length=40)),
                ('telefono', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('empresa_empleadora', models.CharField(blank=True, help_text='Empresa real que emplea o factura a esta persona.', max_length=180)),
                ('tipo_relacion', models.CharField(choices=[('PROPIO', 'Propio'), ('AUTONOMO', 'Autónomo'), ('SUBCONTRATA', 'Subcontrata'), ('EXTERNO', 'Externo'), ('OTRO', 'Otro')], default='PROPIO', max_length=30)),
                ('area_principal', models.CharField(choices=[('OBRA', 'Obra'), ('ADMINISTRACION', 'Administración'), ('COMERCIAL', 'Comercial'), ('GERENCIA', 'Gerencia'), ('ARQUITECTURA', 'Arquitectura'), ('SERVICIOS', 'Servicios'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('puesto', models.CharField(blank=True, max_length=160)),
                ('profesion', models.CharField(blank=True, max_length=160)),
                ('situacion', models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Baja'), ('INACTIVO', 'Inactivo'), ('OTRO', 'Otro')], default='ACTIVO', max_length=20)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('coste_hora', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('precio_bruto_hora', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('coste_bruto_nomina', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('coste_bruto_ss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sueldo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('coeficiente', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('retencion', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('es_fichable', models.BooleanField(default=True)),
                ('es_planificable_obra', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('origen', models.CharField(blank=True, help_text='Origen del dato: manual, seatable, access, importacion, etc.', max_length=40)),
                ('referencia_externa', models.CharField(blank=True, max_length=120)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_empleados', to='usuarios.team')),
                ('user', models.OneToOneField(blank=True, help_text='Usuario del sistema asociado, si lo tiene.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rrhh_empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team', 'nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='GrupoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('OBRA', 'Obra'), ('ADMINISTRACION', 'Administración'), ('COMERCIAL', 'Comercial'), ('GERENCIA', 'Gerencia'), ('ARQUITECTURA', 'Arquitectura'), ('SERVICIOS', 'Servicios'), ('SUBCONTRATA', 'Subcontrata'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_grupos_trabajo', to='usuarios.team')),
            ],
            options={
                'ordering': ['team', 'tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoGrupoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=120)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_grupo', to='rrhh.empleado')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='rrhh.grupotrabajo')),
            ],
            options={
                'ordering': ['empleado', 'grupo'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='grupos_trabajo',
            field=models.ManyToManyField(blank=True, related_name='empleados', through='rrhh.EmpleadoGrupoTrabajo', to='rrhh.grupotrabajo'),
        ),
        migrations.AddIndex(
            model_name='grupotrabajo',
            index=models.Index(fields=['team', 'tipo'], name='idx_rrhh_grupo_team_tipo'),
        ),
        migrations.AddIndex(
            model_name='grupotrabajo',
            index=models.Index(fields=['team', 'activo'], name='idx_rrhh_grupo_activo'),
        ),
        migrations.AddConstraint(
            model_name='grupotrabajo',
            constraint=models.UniqueConstraint(fields=('team', 'nombre'), name='uniq_rrhh_grupo_team_nombre'),
        ),
        migrations.AddIndex(
            model_name='empleadogrupotrabajo',
            index=models.Index(fields=['grupo', 'activo'], name='idx_rrhh_memb_grupo_activo'),
        ),
        migrations.AddIndex(
            model_name='empleadogrupotrabajo',
            index=models.Index(fields=['empleado', 'activo'], name='idx_rrhh_memb_emp_activo'),
        ),
        migrations.AddConstraint(
            model_name='empleadogrupotrabajo',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('empleado', 'grupo'), name='uniq_rrhh_empleado_grupo_activo'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['team', 'situacion'], name='idx_rrhh_emp_situacion'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['team', 'area_principal'], name='idx_rrhh_emp_area'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['team', 'activo'], name='idx_rrhh_emp_activo'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['team', 'nif_nie'], name='idx_rrhh_emp_nif'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['team', 'codigo'], name='idx_rrhh_emp_codigo'),
        ),
    ]
