# Generated by Django 5.0.6 on 2026-08-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_candidatura_cv_sha256_fast_load_v1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('REVISADO', 'Revisado'), ('PRESELECCIONADO', 'Preseleccionado'), ('PENDIENTE_LLAMADA', 'Pendiente de llamada'), ('CONTACTADO', 'Contactado'), ('ENTREVISTA_PROGRAMADA', 'Entrevista programada'), ('ENTREVISTADO', 'Entrevistado'), ('DESCARTADO', 'Descartado'), ('SELECCIONADO', 'Seleccionado'), ('CONTRATADO', 'Contratado')], default='RECIBIDO', max_length=30),
        ),
    ]
