# Generated by Django 5.0.6 on 2026-03-18 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_userprofile_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_externo', models.CharField(db_index=True, help_text='Ej: ATL_3310_001', max_length=100)),
                ('row_id_externo', models.CharField(blank=True, db_index=True, default='', help_text='Row ID único de SeaTable', max_length=100)),
                ('origen', models.CharField(db_index=True, default='seatable', help_text='Sistema origen del registro. Ej: seatable', max_length=50)),
                ('base_origen', models.CharField(blank=True, default='', help_text='Ej: "ACTIVOS INTASA"', max_length=150)),
                ('tabla_origen', models.CharField(blank=True, default='', help_text='Ej: "TODOS LOS ACTIVOS"', max_length=150)),
                ('origen_activo', models.CharField(blank=True, db_index=True, default='', help_text='Valor del desplegable "ACTIVO". Ej: ATLAS', max_length=100)),
                ('estado_operativo', models.CharField(blank=True, db_index=True, default='', help_text='Ej: Sin Atender, Visitada, Desestimado, Para Ofertar', max_length=100)),
                ('gestor_principal', models.CharField(blank=True, db_index=True, default='', help_text='Gestor principal o contenido bruto del campo Gestor', max_length=255)),
                ('historial_resumen', models.TextField(blank=True, default='', help_text='Contenido bruto/resumen del campo Historial')),
                ('situacion_activo', models.CharField(blank=True, db_index=True, default='', help_text='Ej: Pendiente de Cargas, Pendiente de Jaime, etc.', max_length=255)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('valoraciones_raw', models.TextField(blank=True, default='', help_text='Ej: "V-000108, V-000544"')),
                ('visitas_raw', models.TextField(blank=True, default='', help_text='Ej: "VI-0107, VI-0108"')),
                ('cargas_raw', models.TextField(blank=True, default='', help_text='Ej: "C-0239, C-0240"')),
                ('demandas_raw', models.TextField(blank=True, default='', help_text='Ej: "D-010, D-011"')),
                ('fecha_sync', models.DateTimeField(blank=True, help_text='Última fecha/hora de sincronización desde SeaTable', null=True)),
                ('sync_hash', models.CharField(blank=True, db_index=True, default='', help_text='Hash del payload sincronizado para detectar cambios', max_length=64)),
                ('sync_ok', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Activo lógico en INTASA, no confundir con el campo ACTIVO de SeaTable')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='usuarios.team')),
            ],
            options={
                'db_table': 'activos_activo',
                'ordering': ['-updated_at', 'codigo_externo'],
                'indexes': [models.Index(fields=['team', 'origen_activo'], name='activos_act_team_id_792589_idx'), models.Index(fields=['team', 'estado_operativo'], name='activos_act_team_id_627ae3_idx'), models.Index(fields=['team', 'situacion_activo'], name='activos_act_team_id_f361db_idx'), models.Index(fields=['team', 'codigo_externo'], name='activos_act_team_id_3a904b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.UniqueConstraint(fields=('team', 'codigo_externo'), name='uq_activo_team_codigo_externo'),
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.UniqueConstraint(fields=('team', 'row_id_externo'), name='uq_activo_team_row_id_externo'),
        ),
    ]
