# Generated by Django 5.0.6 on 2026-03-18 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
        ('usuarios', '0004_alter_userprofile_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', help_text='Nombre legible del activo', max_length=255)),
                ('codigo_externo', models.CharField(db_index=True, help_text='Código externo principal. Ej: ATL_3310_001', max_length=100)),
                ('row_id_externo', models.CharField(blank=True, db_index=True, default='', help_text='Row ID único del registro origen en SeaTable', max_length=100)),
                ('origen_sistema', models.CharField(choices=[('seatable', 'SeaTable'), ('manual', 'Manual'), ('importacion', 'Importación'), ('api', 'API'), ('otro', 'Otro')], db_index=True, default='seatable', max_length=32)),
                ('base_origen', models.CharField(blank=True, default='', help_text='Ej: "ACTIVOS INTASA"', max_length=150)),
                ('tabla_origen', models.CharField(blank=True, default='', help_text='Ej: "TODOS LOS ACTIVOS"', max_length=150)),
                ('tipo_activo', models.CharField(choices=[('inmobiliario', 'Inmobiliario'), ('intasa', 'INTASA'), ('financiero', 'Financiero'), ('mobiliario', 'Mobiliario'), ('vehiculo', 'Vehículo'), ('otro', 'Otro')], db_index=True, default='inmobiliario', max_length=32)),
                ('origen_activo', models.CharField(blank=True, db_index=True, default='', help_text='Valor del desplegable ACTIVO en SeaTable. Ej: ATLAS', max_length=100)),
                ('estado_operativo', models.CharField(blank=True, choices=[('sin_atender', 'Sin atender'), ('pendiente_visita', 'Pendiente visita'), ('visitada', 'Visitada'), ('desestimado', 'Desestimado'), ('para_ofertar', 'Para ofertar'), ('buena_atender', 'Buena - Atender'), ('otro', 'Otro')], db_index=True, default='', help_text='Normalización del campo Color/estado', max_length=32)),
                ('estado_operativo_raw', models.CharField(blank=True, default='', help_text='Valor bruto original recibido. Ej: "Sin Atender"', max_length=120)),
                ('situacion_activo', models.CharField(blank=True, db_index=True, default='', help_text='Ej: "Pendiente de Cargas"', max_length=255)),
                ('gestor_principal', models.CharField(blank=True, db_index=True, default='', help_text='Nombre o valor bruto del gestor principal', max_length=255)),
                ('gestores_raw', models.TextField(blank=True, default='', help_text='Contenido bruto completo del campo Gestor')),
                ('historial_resumen', models.TextField(blank=True, default='', help_text='Resumen o contenido bruto del historial')),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('ciudad', models.CharField(blank=True, default='', max_length=128)),
                ('provincia', models.CharField(blank=True, default='', max_length=128)),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=16)),
                ('pais', models.CharField(blank=True, default='España', max_length=64)),
                ('valoraciones_raw', models.TextField(blank=True, default='', help_text='Ej: "V-000108, V-000544"')),
                ('visitas_raw', models.TextField(blank=True, default='', help_text='Ej: "VI-0107, VI-0108"')),
                ('cargas_raw', models.TextField(blank=True, default='', help_text='Ej: "C-0239, C-0240"')),
                ('demandas_raw', models.TextField(blank=True, default='', help_text='Ej: "D-010, D-011"')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('crm_disponible', models.BooleanField(db_index=True, default=False, help_text='Indica si puede pasar a circuito comercial/CRM')),
                ('crm_activo', models.BooleanField(db_index=True, default=False, help_text='Indica si ya existe como activo usado en CRM')),
                ('fecha_sync', models.DateTimeField(blank=True, help_text='Última fecha/hora de sincronización', null=True)),
                ('sync_hash', models.CharField(blank=True, db_index=True, default='', help_text='Hash del payload externo para detectar cambios', max_length=64)),
                ('sync_ok', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Activo lógico en el sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos_core', to='usuarios.team')),
            ],
            options={
                'verbose_name': 'Activo CORE',
                'verbose_name_plural': 'Activos CORE',
                'db_table': 'activos_core_activo',
                'ordering': ['-updated_at', 'codigo_externo'],
            },
        ),
        migrations.DeleteModel(
            name='Activo',
        ),
        migrations.AddIndex(
            model_name='activocore',
            index=models.Index(fields=['team', 'tipo_activo'], name='activos_cor_team_id_a5752f_idx'),
        ),
        migrations.AddIndex(
            model_name='activocore',
            index=models.Index(fields=['team', 'origen_activo'], name='activos_cor_team_id_216be1_idx'),
        ),
        migrations.AddIndex(
            model_name='activocore',
            index=models.Index(fields=['team', 'estado_operativo'], name='activos_cor_team_id_c54787_idx'),
        ),
        migrations.AddIndex(
            model_name='activocore',
            index=models.Index(fields=['team', 'situacion_activo'], name='activos_cor_team_id_b1e4f3_idx'),
        ),
        migrations.AddIndex(
            model_name='activocore',
            index=models.Index(fields=['team', 'crm_disponible'], name='activos_cor_team_id_9cf09b_idx'),
        ),
        migrations.AddIndex(
            model_name='activocore',
            index=models.Index(fields=['team', 'crm_activo'], name='activos_cor_team_id_bef3d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='activocore',
            constraint=models.UniqueConstraint(fields=('team', 'codigo_externo'), name='uq_activo_core_team_codigo_externo'),
        ),
        migrations.AddConstraint(
            model_name='activocore',
            constraint=models.UniqueConstraint(condition=models.Q(('row_id_externo', ''), _negated=True), fields=('team', 'row_id_externo'), name='uq_activo_core_team_row_id_externo'),
        ),
    ]
