# Generated by Django 5.0.6 on 2026-03-18 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_activocore_delete_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activocore',
            name='gestor_actual',
            field=models.ForeignKey(blank=True, help_text='Usuario actual responsable del activo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_core_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
