# Generated by Django 5.0.6 on 2026-03-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_activocore_gestor_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='activocore',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Última sincronización desde origen externo', null=True),
        ),
        migrations.AddField(
            model_name='activocore',
            name='origen_sync',
            field=models.CharField(blank=True, default='', help_text='Origen de sincronización externa (ej: seatable)', max_length=32),
        ),
        migrations.AddField(
            model_name='activocore',
            name='seatable_row_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID de fila origen en SeaTable', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activocore',
            name='sync_hash',
            field=models.CharField(blank=True, default='', help_text='Hash para detectar cambios', max_length=64),
        ),
    ]
