# Generated by Django 5.0.6 on 2026-07-26 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.EmailField(max_length=254, unique=True, verbose_name='Dirección de correo')),
                ('nombre_remitente', models.CharField(blank=True, max_length=160, verbose_name='Nombre del remitente')),
                ('imap_host', models.CharField(default='imap.ionos.com', max_length=255, verbose_name='Servidor IMAP')),
                ('imap_port', models.PositiveIntegerField(default=993, verbose_name='Puerto IMAP')),
                ('smtp_host', models.CharField(default='smtp.ionos.com', max_length=255, verbose_name='Servidor SMTP')),
                ('smtp_port', models.PositiveIntegerField(default=465, verbose_name='Puerto SMTP')),
                ('credencial_cifrada', models.TextField(blank=True, editable=False, verbose_name='Credencial cifrada')),
                ('activa', models.BooleanField(default=True, verbose_name='Cuenta activa')),
                ('verificada', models.BooleanField(default=False, editable=False, verbose_name='Conexión verificada')),
                ('ultima_prueba', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Última prueba')),
                ('ultimo_error', models.TextField(blank=True, editable=False, verbose_name='Último error')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_correo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de INTASA')),
            ],
            options={
                'verbose_name': 'cuenta de correo',
                'verbose_name_plural': 'cuentas de correo',
                'ordering': ('usuario__username',),
                'permissions': (('use_correo', 'Puede utilizar el correo corporativo'),),
            },
        ),
    ]
