# Generated by Django 5.0.6 on 2026-07-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacorreo',
            name='imap_host',
            field=models.CharField(default='imap.ionos.es', max_length=255, verbose_name='Servidor IMAP'),
        ),
        migrations.AlterField(
            model_name='cuentacorreo',
            name='smtp_host',
            field=models.CharField(default='smtp.ionos.es', max_length=255, verbose_name='Servidor SMTP'),
        ),
    ]
