# Generated by Django 5.0.6 on 2026-07-19 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
        ('usuarios', '0006_seed_empresa_documental_predeterminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_portal', to='usuarios.team'),
        ),
    ]
