# Generated by Django 5.0.6 on 2025-11-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichajes', '0002_ausencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausencia',
            name='tipo',
            field=models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('PERMISO', 'Permiso retribuido'), ('PERMISO_NR', 'Permiso no retribuido'), ('BAJA', 'Baja médica'), ('ASUNTOS', 'Asuntos propios'), ('FORMACION', 'Formación'), ('OTRA', 'Otra ausencia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fichaje',
            name='tipo',
            field=models.CharField(choices=[('IN', 'Entrada jornada'), ('OUT', 'Salida jornada'), ('PAUSA_IN', 'Inicio pausa'), ('PAUSA_OUT', 'Fin pausa'), ('OTRO_IN', 'Inicio permiso corto'), ('OTRO_OUT', 'Fin permiso corto')], max_length=12),
        ),
    ]
