# Generated by Django 5.0.6 on 2025-12-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichajes', '0003_alter_ausencia_tipo_alter_fichaje_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaje',
            name='location_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar (texto geolocalización)'),
        ),
    ]
