# Generated by Django 5.0.6 on 2025-12-07 16:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichajes', '0004_fichaje_location_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalFichaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(help_text='PIN de 4 dígitos para fichar en el terminal.', max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='El PIN debe tener exactamente 4 dígitos numéricos.', regex='^\\d{4}$')])),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.CharField(blank=True, help_text='Opcional: nota interna (p.ej. Departamento, puesto…).', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_fichaje', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PIN de fichaje',
                'verbose_name_plural': 'PINs de fichaje',
            },
        ),
    ]
