# Generated by Django 5.0.6 on 2025-12-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichajes', '0005_terminalfichaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaje',
            name='origen',
            field=models.CharField(choices=[('PORTAL', 'Portal web'), ('TERMINAL', 'Terminal PIN'), ('OTRO', 'Otro')], db_index=True, default='PORTAL', max_length=10),
        ),
    ]
