# Generated by Django 5.0.6 on 2026-05-20 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichajes', '0006_fichaje_origen'),
        ('usuarios', '0004_alter_userprofile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaje',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Empresa/Team a la que pertenece este fichaje.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichajes', to='usuarios.team'),
        ),
    ]
