# Generated by Django 5.0.6 on 2025-08-17 13:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecursoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referencia', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=255)),
                ('unidad', models.CharField(default='ud', max_length=20)),
                ('precio_ref', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecursoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('especialidad', models.CharField(blank=True, max_length=80)),
                ('coste_hora', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('presupuesto_plan', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='core.obra')),
            ],
            options={
                'ordering': ['obra', 'orden', 'codigo'],
                'unique_together': {('obra', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('baja', 'Baja'), ('otro', 'Otro')], default='vacaciones', max_length=20)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='core.recursopersonal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio_plan', models.DateField(blank=True, null=True)),
                ('fecha_fin_plan', models.DateField(blank=True, null=True)),
                ('horas_plan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coste_plan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='core.capitulo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('PERSONAL', 'Personal'), ('MATERIAL', 'Material')], max_length=10)),
                ('horas_plan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_plan', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('importe_plan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recurso_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planificaciones', to='core.recursomaterial')),
                ('recurso_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planificaciones', to='core.recursopersonal')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='core.tarea')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
