# Generated by Django 5.0.6 on 2025-08-18 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proveedor_partetrabajo_facturaproveedor_vencimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
        migrations.CreateModel(
            name='SubObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, choices=[('VIV', 'Vivienda'), ('ZC', 'Zona común'), ('FCH', 'Fachada'), ('URB', 'Urbanización'), ('JAR', 'Jardines'), ('PIS', 'Piscina'), ('OTR', 'Otro')], max_length=4)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('plan', 'Planificada'), ('activa', 'Activa'), ('cerrada', 'Cerrada')], default='plan', max_length=10)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subobras', to='core.obra')),
            ],
            options={
                'verbose_name': 'Subobra',
                'verbose_name_plural': 'Subobras',
                'ordering': ('obra', 'codigo'),
                'unique_together': {('obra', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='capitulo',
            name='subobra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capitulos', to='core.subobra'),
        ),
    ]
