# Generated by Django 5.0.6 on 2025-11-24 18:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Calendario', max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('PERSONAL', 'Personal'), ('DEPARTAMENTO', 'Departamento'), ('GLOBAL', 'Global')], default='PERSONAL', max_length=20)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('start', models.DateTimeField(verbose_name='Desde')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Hasta')),
                ('all_day', models.BooleanField(default=False, verbose_name='Todo el día')),
                ('rrule', models.TextField(blank=True, default='', verbose_name='Se repite (RRULE)')),
                ('rrule_until', models.DateTimeField(blank=True, null=True, verbose_name='Repetir hasta')),
                ('who_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Quién (texto libre)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('BLOQUEADA', 'Bloqueada'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado tarea')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='Dónde')),
                ('visibility', models.CharField(choices=[('PRIVADA', 'Privada'), ('DEPARTAMENTO', 'Departamento'), ('GLOBAL', 'Global')], default='PRIVADA', max_length=20, verbose_name='Visibilidad')),
                ('obra_id', models.IntegerField(blank=True, null=True)),
                ('obra_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='agenda.calendar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_updated', to=settings.AUTH_USER_MODEL)),
                ('who_users', models.ManyToManyField(blank=True, related_name='agenda_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='agenda/attachments/')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='agenda.event')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_before', models.PositiveIntegerField(default=15)),
                ('channel', models.CharField(default='email', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='agenda.event')),
            ],
        ),
    ]
