# Generated by Django 5.0.6 on 2026-06-30 09:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planificacion_obra', '0008_alter_asignacionobra_options_and_more'),
        ('usuarios', '0004_alter_userprofile_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaObraMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INCIDENCIA', 'Incidencia'), ('SEGURIDAD', 'Seguridad'), ('CALIDAD', 'Calidad'), ('SUMINISTRO', 'Suministro'), ('MAQUINARIA', 'Maquinaria'), ('OTRO', 'Otro')], db_index=True, default='INCIDENCIA', max_length=30)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], db_index=True, default='MEDIA', max_length=20)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_CURSO', 'En curso'), ('RESUELTA', 'Resuelta'), ('CERRADA', 'Cerrada')], db_index=True, default='ABIERTA', max_length=20)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField()),
                ('resolucion', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_obra_movil_cerradas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_obra_movil_creadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_movil', to='planificacion_obra.empleadoobra')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_movil', to='planificacion_obra.obraplanificacion')),
                ('tarea_obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_movil', to='planificacion_obra.tareaobra')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_obra_movil', to='usuarios.team')),
                ('unidad_obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_movil', to='planificacion_obra.unidadobra')),
            ],
            options={
                'verbose_name': 'Incidencia obra móvil',
                'verbose_name_plural': 'Incidencias obra móvil',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['team', 'estado'], name='idx_om_inc_team_estado'), models.Index(fields=['team', 'fecha'], name='idx_om_inc_team_fecha'), models.Index(fields=['obra', 'estado'], name='idx_om_inc_obra_estado')],
            },
        ),
    ]
