# Generated by Django 5.0.6 on 2026-02-24 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(blank=True, max_length=128)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('activo', models.CharField(blank=True, max_length=128)),
                ('tipo_activo', models.CharField(blank=True, max_length=128)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('dorm', models.CharField(blank=True, max_length=32)),
                ('interes', models.CharField(blank=True, max_length=128)),
                ('nombre', models.CharField(max_length=128)),
                ('telefono', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('seatable', models.BooleanField(default=False)),
                ('inmovilla', models.BooleanField(default=False)),
                ('contestada', models.BooleanField(default=False)),
                ('contestada_at', models.DateField(blank=True, null=True)),
                ('seatable_at', models.DateField(blank=True, null=True)),
                ('inmovilla_at', models.DateField(blank=True, null=True)),
                ('visita', models.BooleanField(default=False)),
                ('visita_at', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('prospeccion', 'Prospección'), ('cliente', 'Cliente')], default='nuevo', max_length=24)),
                ('notas', models.TextField(blank=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_as_agente', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_leads', related_query_name='crm_lead', to='usuarios.team')),
            ],
            options={
                'unique_together': {('team', 'email'), ('team', 'telefono')},
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_clientes', related_query_name='crm_cliente', to='usuarios.team')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField(blank=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prospect', to='crm.lead')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_prospects', related_query_name='crm_prospect', to='usuarios.team')),
            ],
        ),
    ]
