# Generated by Django 5.x (equivalente a `makemigrations crm`)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuenteLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=128)),
                ("url", models.URLField(blank=True)),
                ("usuario", models.CharField(max_length=128, blank=True)),
                ("password", models.CharField(max_length=128, blank=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_fuentes",
                        to="usuarios.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Activo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=128)),
                ("direccion", models.CharField(max_length=255, blank=True)),
                ("cod_postal", models.CharField(max_length=16, blank=True)),
                ("ciudad", models.CharField(max_length=128, blank=True)),
                ("provincia", models.CharField(max_length=128, blank=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_activos",
                        to="usuarios.team",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="lead",
            name="interes",
            field=models.TextField(blank=True),
        ),
    ]