# Generated by Django 5.0.6 on 2026-02-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_fuente_activo_fk_tipo_activo_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='activo_lead',
            field=models.BooleanField(default=True),
        ),
    ]
