# Generated by Django 5.0.6 on 2026-05-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion_obra', '0002_rename_unidadobra_planta_to_nivel'),
        ('usuarios', '0004_alter_userprofile_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadobra',
            options={'ordering': ['obra__legacy_cod_obra', 'edificio', 'vivienda', 'nivel'], 'verbose_name': 'Unidad de obra', 'verbose_name_plural': 'Unidades de obra'},
        ),
        migrations.RemoveConstraint(
            model_name='unidadobra',
            name='uniq_po_unidad_legacy_team',
        ),
        migrations.AddConstraint(
            model_name='unidadobra',
            constraint=models.UniqueConstraint(fields=('team', 'obra', 'legacy_cod_fase', 'legacy_cod_vivienda', 'nivel'), name='uniq_po_unidad_legacy_team'),
        ),
    ]
