# Generated by Django 5.0.6 on 2026-05-09 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion_obra', '0003_alter_unidadobra_options_and_more'),
        ('usuarios', '0004_alter_userprofile_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoAlmacenMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id_movimiento', models.IntegerField(db_index=True)),
                ('legacy_id_almacen', models.CharField(blank=True, db_index=True, max_length=40)),
                ('legacy_cod_recurso', models.IntegerField(blank=True, db_index=True, null=True)),
                ('legacy_cod_obra', models.IntegerField(blank=True, db_index=True, null=True)),
                ('legacy_cod_fase', models.IntegerField(blank=True, db_index=True, null=True)),
                ('legacy_cod_vivienda', models.CharField(blank=True, db_index=True, max_length=80)),
                ('legacy_planta', models.CharField(blank=True, max_length=80)),
                ('legacy_capitulo', models.CharField(blank=True, db_index=True, max_length=40)),
                ('legacy_partida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('legacy_cod_personal', models.IntegerField(blank=True, db_index=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=40)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('quedan', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('fecha_movimiento', models.DateField(blank=True, db_index=True, null=True)),
                ('hora_movimiento', models.TimeField(blank=True, null=True)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('CONTROL_STOCK', 'Control stock'), ('ROTURA', 'Rotura'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=30)),
                ('tipo_movimiento_raw', models.CharField(blank=True, max_length=80)),
                ('cod_proveedor', models.CharField(blank=True, max_length=80)),
                ('cod_albaran', models.CharField(blank=True, db_index=True, max_length=80)),
                ('linea', models.IntegerField(blank=True, null=True)),
                ('cod_factura', models.CharField(blank=True, db_index=True, max_length=80)),
                ('en_partida', models.BooleanField(default=False)),
                ('vehiculo', models.CharField(blank=True, max_length=120)),
                ('kilometraje', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='planificacion_obra.almacenobra')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_almacen', to='planificacion_obra.empleadoobra')),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_almacen', to='planificacion_obra.obraplanificacion')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_almacen', to='planificacion_obra.partidacatalogo')),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_almacen', to='planificacion_obra.recursocatalogo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurso_almacen_movimientos', to='usuarios.team')),
                ('unidad_obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_almacen', to='planificacion_obra.unidadobra')),
            ],
            options={
                'verbose_name': 'Movimiento de almacén',
                'verbose_name_plural': 'Movimientos de almacén',
                'ordering': ['-fecha_movimiento', '-legacy_id_movimiento'],
                'indexes': [models.Index(fields=['team', 'fecha_movimiento'], name='idx_po_movalm_fecha'), models.Index(fields=['team', 'tipo_movimiento'], name='idx_po_movalm_tipo'), models.Index(fields=['team', 'legacy_id_almacen'], name='idx_po_movalm_alm'), models.Index(fields=['team', 'legacy_cod_recurso'], name='idx_po_movalm_rec')],
            },
        ),
        migrations.AddConstraint(
            model_name='recursoalmacenmovimiento',
            constraint=models.UniqueConstraint(fields=('team', 'legacy_id_movimiento'), name='uniq_po_movalm_legacy_team'),
        ),
    ]
