# Generated by Django 5.0.6 on 2026-05-09 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion_obra', '0004_recursoalmacenmovimiento_and_more'),
        ('usuarios', '0004_alter_userprofile_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaRecursoPrevisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_row_number', models.IntegerField(db_index=True)),
                ('legacy_cod_obra', models.IntegerField(blank=True, db_index=True, null=True)),
                ('legacy_cod_fase', models.IntegerField(blank=True, db_index=True, null=True)),
                ('legacy_cod_vivienda', models.CharField(blank=True, db_index=True, max_length=80)),
                ('legacy_planta', models.CharField(blank=True, max_length=80)),
                ('legacy_cod_partida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('legacy_id_recurso', models.IntegerField(blank=True, db_index=True, null=True)),
                ('legacy_id_recurso_old', models.IntegerField(blank=True, null=True)),
                ('legacy_orden_recurso', models.IntegerField(blank=True, db_index=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=40)),
                ('precio_unidad', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('costo_recurso', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('control_suministros', models.BooleanField(default=False)),
                ('avisar', models.IntegerField(blank=True, null=True)),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_previstos', to='planificacion_obra.partidacatalogo')),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previstos_en_tareas', to='planificacion_obra.recursocatalogo')),
                ('tarea_obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_previstos', to='planificacion_obra.tareaobra')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea_recursos_previstos', to='usuarios.team')),
                ('unidad_obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_previstos', to='planificacion_obra.unidadobra')),
            ],
            options={
                'verbose_name': 'Recurso previsto de tarea',
                'verbose_name_plural': 'Recursos previstos de tareas',
                'ordering': ['legacy_cod_obra', 'legacy_cod_fase', 'legacy_cod_vivienda', 'legacy_planta', 'legacy_cod_partida', 'legacy_orden_recurso', 'legacy_row_number'],
                'indexes': [models.Index(fields=['team', 'legacy_cod_obra'], name='idx_po_recprev_obra'), models.Index(fields=['team', 'legacy_id_recurso'], name='idx_po_recprev_recurso'), models.Index(fields=['team', 'legacy_cod_partida'], name='idx_po_recprev_partida')],
            },
        ),
        migrations.AddConstraint(
            model_name='tarearecursoprevisto',
            constraint=models.UniqueConstraint(fields=('team', 'legacy_row_number'), name='uniq_po_recurso_previsto_row_team'),
        ),
    ]
