# Generated by Django 5.0.6 on 2026-05-10 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion_obra', '0005_tarearecursoprevisto_and_more'),
        ('usuarios', '0004_alter_userprofile_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaRecursoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id_recurso_tarea', models.IntegerField(db_index=True)),
                ('legacy_cod_obra', models.IntegerField(blank=True, db_index=True, null=True)),
                ('legacy_cod_fase', models.IntegerField(blank=True, db_index=True, null=True)),
                ('legacy_cod_vivienda', models.CharField(blank=True, db_index=True, max_length=80)),
                ('legacy_planta', models.CharField(blank=True, max_length=80)),
                ('legacy_capitulo', models.CharField(blank=True, db_index=True, max_length=40)),
                ('legacy_partida', models.CharField(blank=True, db_index=True, max_length=40)),
                ('legacy_id_recurso', models.IntegerField(blank=True, db_index=True, null=True)),
                ('legacy_tipo_recurso', models.CharField(blank=True, db_index=True, max_length=80)),
                ('legacy_personal', models.IntegerField(blank=True, null=True)),
                ('legacy_id_movimiento_almacen', models.IntegerField(blank=True, db_index=True, null=True)),
                ('legacy_orden_recurso', models.IntegerField(blank=True, db_index=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=40)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('precio_unidad', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('dias', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('dias_reales', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('horas', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('horas_reales', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('inicio_recurso_real', models.DateField(blank=True, null=True)),
                ('fin_recurso_real', models.DateField(blank=True, null=True)),
                ('costo_recurso', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('costo_recurso_real', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('control_suministros', models.BooleanField(default=False)),
                ('avisar', models.IntegerField(blank=True, null=True)),
                ('id_proveedor', models.CharField(blank=True, max_length=80)),
                ('cod_albaran', models.CharField(blank=True, max_length=80)),
                ('num_linea_albaran', models.IntegerField(blank=True, null=True)),
                ('cod_factura', models.CharField(blank=True, max_length=80)),
                ('num_linea_factura', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_reales', to='planificacion_obra.empleadoobra')),
                ('movimiento_almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_reales_tarea', to='planificacion_obra.recursoalmacenmovimiento')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_reales', to='planificacion_obra.partidacatalogo')),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reales_en_tareas', to='planificacion_obra.recursocatalogo')),
                ('tarea_obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_reales', to='planificacion_obra.tareaobra')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea_recursos_reales', to='usuarios.team')),
                ('unidad_obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_reales', to='planificacion_obra.unidadobra')),
            ],
            options={
                'verbose_name': 'Recurso real de tarea',
                'verbose_name_plural': 'Recursos reales de tareas',
                'ordering': ['legacy_cod_obra', 'legacy_cod_fase', 'legacy_cod_vivienda', 'legacy_planta', 'legacy_partida', 'legacy_orden_recurso', 'legacy_id_recurso_tarea'],
                'indexes': [models.Index(fields=['team', 'legacy_cod_obra'], name='idx_po_recreal_obra'), models.Index(fields=['team', 'legacy_id_recurso'], name='idx_po_recreal_idrec'), models.Index(fields=['team', 'legacy_tipo_recurso'], name='idx_po_recreal_tipo'), models.Index(fields=['team', 'legacy_partida'], name='idx_po_recreal_partida')],
            },
        ),
        migrations.AddConstraint(
            model_name='tarearecursoreal',
            constraint=models.UniqueConstraint(fields=('team', 'legacy_id_recurso_tarea'), name='uniq_po_recurso_real_legacy_team'),
        ),
    ]
