# Generated by Django 5.0.6 on 2026-05-10 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion_obra', '0006_tarearecursoreal_and_more'),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadoobra',
            name='rrhh_empleado',
            field=models.ForeignKey(blank=True, help_text='Empleado maestro RRHH asociado a este empleado legacy de obra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_obra_legacy', to='rrhh.empleado'),
        ),
    ]
