# Generated by Django 5.0.6 on 2026-05-10 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion_obra', '0007_empleadoobra_rrhh_empleado'),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionobra',
            options={'ordering': ['fecha_inicio', 'hora_inicio', 'empleado__nombre_completo'], 'verbose_name': 'Asignación de obra', 'verbose_name_plural': 'Asignaciones de obra'},
        ),
        migrations.AlterField(
            model_name='asignacionobra',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_obra', to='rrhh.empleado'),
        ),
    ]
