import uuid

import comparativas.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
        (
            "usuarios",
            "0006_seed_empresa_documental_predeterminada",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Comparativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=180
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        max_length=120,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            (
                                "BORRADOR",
                                "Borrador",
                            ),
                            (
                                "EN_COMPARACION",
                                "En comparación",
                            ),
                            (
                                "PENDIENTE_DECISION",
                                "Pendiente de decisión",
                            ),
                            (
                                "ADJUDICADA",
                                "Adjudicada",
                            ),
                            (
                                "CERRADA",
                                "Cerrada",
                            ),
                        ],
                        db_index=True,
                        default="BORRADOR",
                        max_length=30,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "Alcance que deben cubrir "
                            "las ofertas para considerarse "
                            "comparables."
                        ),
                    ),
                ),
                (
                    "referencia_tipo",
                    models.CharField(
                        blank=True,
                        max_length=120,
                    ),
                ),
                (
                    "referencia_id",
                    models.CharField(
                        blank=True,
                        max_length=80,
                    ),
                ),
                (
                    "referencia_codigo",
                    models.CharField(
                        blank=True,
                        max_length=120,
                    ),
                ),
                (
                    "referencia_nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=(
                            django.db.models.deletion
                            .SET_NULL
                        ),
                        related_name=(
                            "comparativas_creadas"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=(
                            django.db.models.deletion
                            .SET_NULL
                        ),
                        related_name=(
                            "comparativas_responsable"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion
                            .PROTECT
                        ),
                        related_name="comparativas",
                        to="usuarios.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comparativa",
                "verbose_name_plural": (
                    "Comparativas"
                ),
                "ordering": (
                    "-updated_at",
                    "-id",
                ),
                "permissions": (
                    (
                        "access_comparativas",
                        (
                            "Puede acceder "
                            "a comparativas"
                        ),
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="Ofertante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            (
                                "PROVEEDOR",
                                "Proveedor existente",
                            ),
                            (
                                "CANDIDATO",
                                "Candidato",
                            ),
                        ],
                        default="CANDIDATO",
                        max_length=20,
                    ),
                ),
                (
                    "proveedor_ref_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255
                    ),
                ),
                (
                    "nif",
                    models.CharField(
                        blank=True,
                        max_length=60,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        max_length=80,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            (
                                "ACTIVO",
                                "Activo",
                            ),
                            (
                                "ADJUDICADO",
                                "Adjudicado",
                            ),
                            (
                                "DESCARTADO",
                                "Descartado",
                            ),
                        ],
                        db_index=True,
                        default="ACTIVO",
                        max_length=20,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True
                    ),
                ),
                (
                    "comparativa",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion
                            .CASCADE
                        ),
                        related_name="ofertantes",
                        to="comparativas.comparativa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ofertante",
                "verbose_name_plural": (
                    "Ofertantes"
                ),
                "ordering": (
                    "nombre",
                    "id",
                ),
            },
        ),
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(),
                ),
                (
                    "fecha_documento",
                    models.DateField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        max_length=160,
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        default="EUR",
                        max_length=3,
                    ),
                ),
                (
                    "base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "impuestos",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            (
                                "RECIBIDA",
                                "Recibida",
                            ),
                            (
                                "PENDIENTE_ANALISIS",
                                (
                                    "Pendiente "
                                    "de análisis"
                                ),
                            ),
                            (
                                "ANALIZADA",
                                "Analizada",
                            ),
                            (
                                "REVISAR",
                                "Revisar alcance",
                            ),
                            (
                                "VALIDADA",
                                "Validada",
                            ),
                            (
                                "DESCARTADA",
                                "Descartada",
                            ),
                        ],
                        db_index=True,
                        default="RECIBIDA",
                        max_length=30,
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=(
                            django.db.models.deletion
                            .SET_NULL
                        ),
                        related_name=(
                            "comparativas_ofertas_creadas"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ofertante",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion
                            .CASCADE
                        ),
                        related_name="ofertas",
                        to="comparativas.ofertante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oferta",
                "verbose_name_plural": "Ofertas",
                "ordering": (
                    "-version",
                    "-id",
                ),
            },
        ),
        migrations.CreateModel(
            name="DocumentoComparativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        max_length=500,
                        upload_to=(
                            comparativas.models
                            .documento_upload_to
                        ),
                    ),
                ),
                (
                    "nombre_original",
                    models.CharField(
                        max_length=255
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True,
                        max_length=20,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        max_length=160,
                    ),
                ),
                (
                    "tamano_bytes",
                    models.PositiveBigIntegerField(
                        default=0
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "estado_analisis",
                    models.CharField(
                        choices=[
                            (
                                "PENDIENTE",
                                "Pendiente",
                            ),
                            (
                                "PROCESANDO",
                                "Procesando",
                            ),
                            (
                                "COMPLETADO",
                                "Completado",
                            ),
                            (
                                "ERROR",
                                "Error",
                            ),
                            (
                                "NO_APLICA",
                                "No aplica",
                            ),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "texto_extraido",
                    models.TextField(
                        blank=True
                    ),
                ),
                (
                    "datos_extraidos",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "error_analisis",
                    models.TextField(
                        blank=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True
                    ),
                ),
                (
                    "oferta",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion
                            .CASCADE
                        ),
                        related_name="documentos",
                        to="comparativas.oferta",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=(
                            django.db.models.deletion
                            .SET_NULL
                        ),
                        related_name=(
                            "comparativas_documentos_subidos"
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": (
                    "Documento de comparativa"
                ),
                "verbose_name_plural": (
                    "Documentos de comparativa"
                ),
                "ordering": (
                    "-created_at",
                    "-id",
                ),
            },
        ),
        migrations.AddIndex(
            model_name="comparativa",
            index=models.Index(
                fields=[
                    "team",
                    "estado",
                ],
                name="cmp_team_estado_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comparativa",
            index=models.Index(
                fields=[
                    "referencia_tipo",
                    "referencia_id",
                ],
                name="cmp_ref_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ofertante",
            index=models.Index(
                fields=[
                    "comparativa",
                    "estado",
                ],
                name="cmp_ofert_comp_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="oferta",
            constraint=models.UniqueConstraint(
                fields=(
                    "ofertante",
                    "version",
                ),
                name=(
                    "cmp_oferta_version_unique"
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="oferta",
            index=models.Index(
                fields=[
                    "ofertante",
                    "estado",
                ],
                name="cmp_oferta_estado_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentocomparativa",
            index=models.Index(
                fields=[
                    "oferta",
                    "estado_analisis",
                ],
                name="cmp_doc_estado_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentocomparativa",
            index=models.Index(
                fields=["sha256"],
                name="cmp_doc_sha_idx",
            ),
        ),
    ]
