from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "comparativas",
            "0001_initial",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptoOferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0,
                    ),
                ),
                (
                    "codigo_original",
                    models.CharField(
                        blank=True,
                        max_length=120,
                    ),
                ),
                (
                    "titulo_original",
                    models.CharField(
                        blank=True,
                        max_length=500,
                    ),
                ),
                (
                    "descripcion_original",
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    "texto_normalizado",
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        blank=True,
                        max_length=40,
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "alcance",
                    models.CharField(
                        choices=[
                            (
                                "INCLUIDO",
                                "Incluido",
                            ),
                            (
                                "EXCLUIDO",
                                "Excluido",
                            ),
                            (
                                "INFORMATIVO",
                                "Informativo",
                            ),
                            (
                                "REVISAR",
                                "Revisar",
                            ),
                        ],
                        db_index=True,
                        default="REVISAR",
                        max_length=20,
                    ),
                ),
                (
                    "pagina",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "linea_inicio",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "linea_fin",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "evidencia",
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            (
                                "DETERMINISTA",
                                "Determinista",
                            ),
                            (
                                "IA",
                                "IA",
                            ),
                            (
                                "HUMANO",
                                "Humano",
                            ),
                        ],
                        default="DETERMINISTA",
                        max_length=20,
                    ),
                ),
                (
                    "confianza_extraccion",
                    models.CharField(
                        choices=[
                            (
                                "MUY_ALTA",
                                "Muy alta",
                            ),
                            (
                                "ALTA",
                                "Alta",
                            ),
                            (
                                "REVISAR",
                                "Revisar",
                            ),
                        ],
                        db_index=True,
                        default="REVISAR",
                        max_length=20,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=(
                            django.db.models.deletion
                            .SET_NULL
                        ),
                        related_name=(
                            "conceptos_extraidos"
                        ),
                        to=(
                            "comparativas."
                            "documentocomparativa"
                        ),
                    ),
                ),
                (
                    "oferta",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion
                            .CASCADE
                        ),
                        related_name="conceptos",
                        to="comparativas.oferta",
                    ),
                ),
            ],
            options={
                "verbose_name": (
                    "Concepto de oferta"
                ),
                "verbose_name_plural": (
                    "Conceptos de oferta"
                ),
                "ordering": (
                    "oferta_id",
                    "orden",
                    "id",
                ),
            },
        ),

        migrations.CreateModel(
            name="GrupoComparacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            (
                                "PROPUESTO",
                                "Propuesto",
                            ),
                            (
                                "VALIDADO",
                                "Validado",
                            ),
                            (
                                "DESCARTADO",
                                "Descartado",
                            ),
                        ],
                        db_index=True,
                        default="PROPUESTO",
                        max_length=20,
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            (
                                "DETERMINISTA",
                                "Determinista",
                            ),
                            (
                                "IA",
                                "IA",
                            ),
                            (
                                "HUMANO",
                                "Humano",
                            ),
                        ],
                        default="DETERMINISTA",
                        max_length=20,
                    ),
                ),
                (
                    "confianza",
                    models.CharField(
                        choices=[
                            (
                                "MUY_ALTA",
                                "Muy alta",
                            ),
                            (
                                "ALTA",
                                "Alta",
                            ),
                            (
                                "REVISAR",
                                "Revisar",
                            ),
                        ],
                        default="REVISAR",
                        max_length=20,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "comparativa",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion
                            .CASCADE
                        ),
                        related_name=(
                            "grupos_comparacion"
                        ),
                        to=(
                            "comparativas."
                            "comparativa"
                        ),
                    ),
                ),
            ],
            options={
                "verbose_name": (
                    "Grupo de comparación"
                ),
                "verbose_name_plural": (
                    "Grupos de comparación"
                ),
                "ordering": (
                    "comparativa_id",
                    "orden",
                    "id",
                ),
            },
        ),

        migrations.CreateModel(
            name="RelacionConcepto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confianza_coincidencia",
                    models.CharField(
                        choices=[
                            (
                                "MUY_ALTA",
                                "Muy alta",
                            ),
                            (
                                "ALTA",
                                "Alta",
                            ),
                            (
                                "REVISAR",
                                "Revisar",
                            ),
                        ],
                        db_index=True,
                        default="REVISAR",
                        max_length=20,
                    ),
                ),
                (
                    "estado_revision",
                    models.CharField(
                        choices=[
                            (
                                "PROPUESTA",
                                "Propuesta",
                            ),
                            (
                                "VALIDADA",
                                "Validada",
                            ),
                            (
                                "RECHAZADA",
                                "Rechazada",
                            ),
                        ],
                        db_index=True,
                        default="PROPUESTA",
                        max_length=20,
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            (
                                "DETERMINISTA",
                                "Determinista",
                            ),
                            (
                                "IA",
                                "IA",
                            ),
                            (
                                "HUMANO",
                                "Humano",
                            ),
                        ],
                        default="DETERMINISTA",
                        max_length=20,
                    ),
                ),
                (
                    "explicacion",
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion
                            .CASCADE
                        ),
                        related_name=(
                            "relaciones_comparacion"
                        ),
                        to=(
                            "comparativas."
                            "conceptooferta"
                        ),
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models.deletion
                            .CASCADE
                        ),
                        related_name="relaciones",
                        to=(
                            "comparativas."
                            "grupocomparacion"
                        ),
                    ),
                ),
            ],
            options={
                "verbose_name": (
                    "Relación de concepto"
                ),
                "verbose_name_plural": (
                    "Relaciones de conceptos"
                ),
                "ordering": (
                    "grupo_id",
                    "id",
                ),
            },
        ),

        migrations.AddIndex(
            model_name="conceptooferta",
            index=models.Index(
                fields=[
                    "oferta",
                    "orden",
                ],
                name="cmp_conc_oferta_ord_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="conceptooferta",
            index=models.Index(
                fields=[
                    "documento",
                    "pagina",
                ],
                name="cmp_conc_doc_pag_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="conceptooferta",
            index=models.Index(
                fields=[
                    "oferta",
                    "alcance",
                ],
                name="cmp_conc_oferta_alc_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="grupocomparacion",
            index=models.Index(
                fields=[
                    "comparativa",
                    "orden",
                ],
                name="cmp_grp_comp_ord_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="grupocomparacion",
            index=models.Index(
                fields=[
                    "comparativa",
                    "estado",
                ],
                name="cmp_grp_comp_est_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="relacionconcepto",
            index=models.Index(
                fields=[
                    "grupo",
                    "estado_revision",
                ],
                name="cmp_rel_grp_est_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="relacionconcepto",
            index=models.Index(
                fields=[
                    "concepto",
                    "estado_revision",
                ],
                name="cmp_rel_conc_est_idx",
            ),
        ),

        migrations.AddConstraint(
            model_name="relacionconcepto",
            constraint=models.UniqueConstraint(
                fields=(
                    "grupo",
                    "concepto",
                ),
                name="cmp_rel_grupo_conc_uq",
            ),
        ),
    ]
