# Generated by Django 5.0.6 on 2026-07-18 07:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_userprofile_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(db_index=True, max_length=50)),
                ('accion', models.CharField(db_index=True, max_length=50)),
                ('tipo_objeto', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('objeto_repr', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('visibilidad', models.CharField(choices=[('ACTOR', 'Solo actor'), ('EQUIPO', 'Equipo'), ('OBJETO', 'Según permisos del objeto')], db_index=True, default='EQUIPO', max_length=20)),
                ('origen', models.CharField(choices=[('EXPLICITO', 'Servicio explícito'), ('SENAL', 'Señal Django'), ('IMPORTACION', 'Importación'), ('SISTEMA', 'Sistema')], db_index=True, default='EXPLICITO', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('agrupacion_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('clave_idempotencia', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('visible_en_dashboard', models.BooleanField(db_index=True, default=True)),
                ('ocurrida_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_plataforma', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_plataforma', to='usuarios.team')),
            ],
            options={
                'verbose_name': 'Actividad de plataforma',
                'verbose_name_plural': 'Actividades de plataforma',
                'ordering': ('-ocurrida_en', '-id'),
                'permissions': (('view_team_activity', 'Puede ver la actividad de su equipo'), ('view_all_activity', 'Puede ver toda la actividad permitida')),
                'indexes': [models.Index(fields=['team', '-ocurrida_en'], name='act_team_fecha_idx'), models.Index(fields=['actor', '-ocurrida_en'], name='act_actor_fecha_idx'), models.Index(fields=['modulo', '-ocurrida_en'], name='act_mod_fecha_idx'), models.Index(fields=['accion', '-ocurrida_en'], name='act_acc_fecha_idx'), models.Index(fields=['team', 'modulo', '-ocurrida_en'], name='act_team_mod_fecha_idx'), models.Index(fields=['agrupacion_key', '-ocurrida_en'], name='act_group_fecha_idx')],
            },
        ),
    ]
