# Generated by Django 5.0.6 on 2026-07-25 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_seed_empresa_documental_predeterminada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nueva conversación', max_length=160)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ARCHIVADA', 'Archivada')], db_index=True, default='ACTIVA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversaciones_intasa_ia', to='usuarios.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_intasa_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación INTASA IA',
                'verbose_name_plural': 'Conversaciones INTASA IA',
                'ordering': ('-updated_at', '-id'),
                'permissions': (('use_intasa_ia', 'Puede utilizar INTASA IA'), ('view_all_ia_conversations', 'Puede consultar todas las conversaciones IA')),
            },
        ),
        migrations.CreateModel(
            name='MensajeIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('USUARIO', 'Usuario'), ('ASISTENTE', 'Asistente'), ('SISTEMA', 'Sistema')], db_index=True, max_length=20)),
                ('contenido', models.TextField()),
                ('proveedor', models.CharField(blank=True, default='', max_length=50)),
                ('modelo', models.CharField(blank=True, default='', max_length=100)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('tokens_entrada', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_salida', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='intasa_ia.conversacionia')),
            ],
            options={
                'verbose_name': 'Mensaje INTASA IA',
                'verbose_name_plural': 'Mensajes INTASA IA',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='conversacionia',
            index=models.Index(fields=['user', '-updated_at'], name='ia_conv_usr_upd'),
        ),
        migrations.AddIndex(
            model_name='conversacionia',
            index=models.Index(fields=['team', '-updated_at'], name='ia_conv_team_upd'),
        ),
        migrations.AddIndex(
            model_name='mensajeia',
            index=models.Index(fields=['conversacion', 'created_at'], name='ia_msg_conv_fecha'),
        ),
    ]
