# Generated by Django 5.0.6 on 2026-07-26 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intasa_ia', '0001_initial'),
        ('usuarios', '0006_seed_empresa_documental_predeterminada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacionia',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_intasa_ia', to='usuarios.team'),
        ),
        migrations.CreateModel(
            name='AccesoConversacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_compartidos', to='intasa_ia.conversacionia')),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_intasa_ia_compartidas', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_conversaciones_intasa_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso compartido INTASA IA',
                'verbose_name_plural': 'Accesos compartidos INTASA IA',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='ia_share_usr_fecha'), models.Index(fields=['conversacion', 'user'], name='ia_share_conv_usr')],
            },
        ),
        migrations.AddConstraint(
            model_name='accesoconversacionia',
            constraint=models.UniqueConstraint(fields=('conversacion', 'user'), name='ia_share_unique'),
        ),
    ]
