# Generated by Django 5.0.6 on 2026-03-18 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='color',
            field=models.CharField(default='#3498DB', max_length=7, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato hex (#RRGGBB)', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
